on: [pull_request, pull_request_review, pull_request_review_comment]

permissions: write-all

jobs:
  t:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo 'The PR was merged {{github.event}}'
